kurs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
# from django.contrib.auth import logout
from django.template.defaulttags import url
from django.urls import path, include

from kurs import settings
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('workouts/', workouts, name='workouts'),
    path('workouts/<slug:slug>/', workout, name='workout'),
    path('exercises/', exercises_page, name='exercises'),
    path('exercise/<slug:slug>/', exercise_page, name='exercise'),
    path('recipes/', recipes, name='recipes'),
    path('recipes/<slug:slug>/', recipes, name='recipe'),
    path('lk/add_workout/', add_workout, name='add_workout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_user, name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('start_workout/<slug:slug>/', start_workout, name='start_workout'),
    path('diary/', diary, name='diary'),
    path('diary_note/<str:curr_date>/', diary_note, name='diary_note'),
    path('workout_day/<int:pk>/<int:day>/', workout_day, name='workout_day'),
    path('diary_note_exist/<str:curr_date>/', diary_note_exist, name='diary_note_exist'),

    # path('logout/', logout, name='logout'),
]

main/models.py
from django.db import models
from django.db.models import SET_NULL, CASCADE
from django.contrib.auth.models import User


complexity = (
    ('light', 'light'),
    ('middle', 'middle'),
    ('hard', 'hard'),
)


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Inventory(models.Model):
    inventory = models.CharField(max_length=100)

    def __str__(self):
        return self.inventory


class Trainer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gym = models.CharField(max_length=100)
    experience = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username


class Workout(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    desc = models.TextField()
    views = models.PositiveIntegerField(default=0)
    photo = models.ImageField(null=True)
    complexity = models.CharField(max_length=100, choices=complexity)
    inventory = models.ForeignKey('Inventory', null=True, on_delete=SET_NULL)
    category = models.ForeignKey('Category', null=True, on_delete=SET_NULL)
    trainer = models.ForeignKey('Trainer', null=True, on_delete=SET_NULL)

    def __str__(self):
        return self.name


class Exercise(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    desc = models.TextField()
    photo = models.ImageField(null=True, blank=True)
    video = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name


class ExerciseInWorkout(models.Model):
    approaches = models.PositiveSmallIntegerField()
    repetitions = models.PositiveSmallIntegerField()
    weight = models.PositiveSmallIntegerField(null=True, blank=True)
    day = models.CharField(max_length=100)
    number = models.PositiveSmallIntegerField()
    workout = models.ForeignKey('Workout', null=True, on_delete=SET_NULL)
    exercise = models.ForeignKey('Exercise', null=True, on_delete=SET_NULL)

    def __str__(self):
        return f'{self.exercise.name}\n' \
               f'Подходы: {self.approaches}\n' \
               f'Повторения: {self.repetitions}\n\n'


class UserWorkout(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    workout = models.ForeignKey('Workout', on_delete=CASCADE)


class Recipe(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=500)
    ings = models.TextField(null=True)
    slug = models.SlugField(null=True)
    photo = models.ImageField(null=True)
    author = models.ForeignKey(User, null=True, on_delete=SET_NULL)

    def __str__(self):
        return self.title


class RecipeStep(models.Model):
    text = models.TextField()
    number = models.PositiveSmallIntegerField(null=True, default=0)
    photo = models.ImageField(null=True)
    recipe = models.ForeignKey('Recipe', null=True, on_delete=SET_NULL)


class ActiveWorkout(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    workout = models.ForeignKey('Workout', on_delete=CASCADE)

    def __str__(self):
        return self.workout.name


class Event(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    workout = models.ForeignKey('ActiveWorkout', null=True, on_delete=SET_NULL)
    date = models.DateField()
    text = models.TextField()

main/forms.py
from django import forms
from django.forms import ModelForm, Textarea, Select
from .models import *

DAYS = (
    (1, 'День 1'),
    (2, 'День 2'),
    (3, 'День 3'),
    (4, 'День 4'),
)


class EventForm(ModelForm):
    date = forms.DateField(input_formats=['%d/%m/%Y'])
    day = forms.ChoiceField(choices=DAYS, widget=forms.Select(attrs={'class': 'form-control'}))
    text = forms.Textarea()
    workout = forms.ModelChoiceField(queryset=ActiveWorkout.objects.all(),
                                     widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Event
        fields = ['date', 'text', 'workout', ]
        widgets = {
            'text': Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }

main/views.py
from datetime import datetime

from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.db.models import Q
from calendar import HTMLCalendar
from datetime import date
import calendar
from .forms import EventForm
from .models import *

menu = {'Главная': 'home', 'Тренировки': 'workouts', 'Упражнения': 'exercises', 'Рецепты': 'recipes',
        'Дневник тренировок': 'home'}


def home(request):
    active_workouts = None
    if request.user.is_authenticated:
        active_workouts = ActiveWorkout.objects.filter(user=request.user)
    workouts = Workout.objects.order_by('-views')[:12]
    recipes = Recipe.objects.all()
    return render(request, 'main/home.html', context={'workouts': workouts, 'title': 'Главная', 'menu': menu,
                                                      'active_workouts': active_workouts, 'recipes': recipes})


def workouts(request):
    active_workouts = None
    if request.user.is_authenticated:
        active_workouts = ActiveWorkout.objects.filter(user=request.user)
    workouts = Workout.objects.all()
    return render(request, 'main/workouts.html', context={'workouts': workouts, 'title': 'Тренировки', 'menu': menu,
                                                          'active_workouts': active_workouts})


def workout(request, slug=None):
    current_workout = Workout.objects.get(slug=slug)
    active = None
    if request.user.is_authenticated:
        active = ActiveWorkout.objects.filter(workout=current_workout, user=request.user)
    exercises_1 = ExerciseInWorkout.objects.filter(workout=current_workout, day=1)
    exercises_2 = ExerciseInWorkout.objects.filter(workout=current_workout, day=2)
    exercises_3 = ExerciseInWorkout.objects.filter(workout=current_workout, day=3)
    exercises_4 = ExerciseInWorkout.objects.filter(workout=current_workout, day=4)
    return render(request, 'main/workout.html', context={'workout': current_workout, 'title': 'Тренировки', 'menu': menu,
                                                         'exercises_1': exercises_1, 'exercises_2': exercises_2,
                                                         'exercises_3': exercises_3, 'exercises_4': exercises_4,
                                                         'active': active})


def exercises_page(request):
    query = request.GET.get('q')
    if query is not None:
        guide_exercises = Exercise.objects.filter(Q(name__iregex=query) | Q(desc__iregex=query))
    else:
        guide_exercises = Exercise.objects.all()
    return render(request, 'main/exercises.html', context={'guide_exercises': guide_exercises, 'title':
                                                           'Упражнения', 'menu': menu})


def exercise_page(request, slug=None):
    guide_exercise = Exercise.objects.get(slug=slug)
    return render(request, 'main/exercise.html', context={'guide_exercise': guide_exercise, 'title':
                                                           'Упражнения', 'menu': menu})


def user_workouts(request):
    if request.user.is_authenticated():
        # current_user = User.objects.get(pk=request.user)
        workouts = Workout.objects.filter(user=request.user)
        return render(request, 'main/index.html', context={'workouts': workouts})
    else:
        return render(request, 'main/403.html')


def add_workout(request):
    if request.method == 'POST':
        pass


def start_workout(request, slug=None):
    curr_workout = Workout.objects.get(slug=slug)
    ActiveWorkout.objects.create(workout=curr_workout, user=request.user).save()
    return redirect('workout', slug)


def recipes(request, slug=None):
    recipes, current_recipe, steps = None, None, None
    if slug is None:
        recipes = Recipe.objects.all()
    else:
        current_recipe = Recipe.objects.get(slug=slug)
        steps = RecipeStep.objects.filter(recipe=current_recipe)
    return render(request, 'main/recipes.html', context={'recipe': current_recipe, 'recipes': recipes, 'steps': steps,
                                                         'title': 'Рецепты', 'menu': menu})


def diary(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.user = request.user
            event.save()
            return HttpResponseRedirect(reverse('diary'))

    year, month = None, None
    if request.method == 'GET':
        month = request.GET.get('month')
        year = request.GET.get('year')

    if year is None:
        year = datetime.now().year
    if month is None:
        month = datetime.now().month

    form = EventForm(initial={workout: ActiveWorkout.objects.filter(user=request.user)})
    print(form)
    a = calendar.LocaleHTMLCalendar().formatmonth(int(year), int(month), withyear=True)
    return render(request, 'main/diary.html', context={'title': 'Дневник тренировок', 'menu': menu,
                                                       'form': form, 'calendar': a})


def diary_note(request, curr_date):
    note = Event.objects.filter(date=curr_date).last()
    if note is not None:
        return HttpResponse("{} - {} ={}".format(note.date, note.workout, note.text))
    else:
        return HttpResponse("=")


def diary_note_exist(request, curr_date):
    return HttpResponse('0') if Event.objects.filter(date=curr_date).last() is None else HttpResponse('1')


def workout_day(request, pk, day):
    work = ActiveWorkout.objects.get(pk=pk).workout

    return HttpResponse(ExerciseInWorkout.objects.filter(workout=work, day=day))


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


def logout_user(request):
    logout(request)
    return redirect('home')

main/templates/main/diary.html
{% extends 'main/index.html' %}
{% block main %}

    <div class="row">
        <div class="col-md-6">
            {{calendar |safe}}
        </div>
        <div class="col-md-3" style="margin-top:5rem;">
            <div class="col-md-3" style="margin-right:40rem;">
                <div class="card" style="width: 40rem; margin-right: 2rem; margin-bottom: 2rem;">
                    <div class="card card-body">
                        <h5 class="card-title" id="title"></h5>
                        <textarea class="form-control" id="text" rows="12" readonly="readonly" style="overflow:auto; resize:none"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div><br><br>

    <div class="row">
        <div class="col-md-3 mx-auto text-center" style="margin-right:40rem;">
            <form action="{% url 'diary' %}" method="post">{% csrf_token %}
                {{ form.date }} <br>
                {{ form.workout }} <br>
                {{ form.day }} <br>
                {{ form.text }} <br>

                <script>
                  $(function () {
                    $("#id_date").datepicker({
                      format:'dd/mm/yyyy',
                    });
                    $("#id_date").addClass('form-control');
                  });

                  $(function () {
                    $("td").each(function() {
                        let m = $("th[class='month']").text();
                        m = m.split(' ');
                        if (m[0] == 'января') { m[0] = '01' }
                        if (m[0] == 'февраля') { m[0] = '02' }
                        if (m[0] == 'марта') { m[0] = '03' }
                        if (m[0] == 'апреля') { m[0] = '04' }
                        if (m[0] == 'мая') { m[0] = '05' }
                        if (m[0] == 'июня') { m[0] = '06' }
                        if (m[0] == 'июля') { m[0] = '07' }
                        if (m[0] == 'августа') { m[0] = '08' }
                        if (m[0] == 'сентябрь') { m[0] = '09' }
                        if (m[0] == 'октября') { m[0] = '10' }
                        if (m[0] == 'ноября') { m[0] = '11' }
                        if ((m[0] == 'декабря') || (m[0] == 'December')) { m[0] = '12' }

                        let id = $(this).text();
                        if (id=='\xa0') { return; };
                        let date = m[1]+'-'+m[0]+'-'+id;

                        var that = $(this);
                        $.get('http://fkolonistov.pythonanywhere.com/diary_note_exist/'+date, function(data) {
                           if (data == '1') { $(that).css("font-weight", "bold"); }
                           else { $(that).css("color", "#3b3b3b"); };

                        });
                    });
                  });

                  $(function () {
                    $("td").on('click', function(){
                        let m = $("th[class='month']").text();
                        m = m.split(' ');
                        if (m[0] == 'января') { m[0] = '01' }
                        if (m[0] == 'февраля') { m[0] = '02' }
                        if (m[0] == 'марта') { m[0] = '03' }
                        if (m[0] == 'апреля') { m[0] = '04' }
                        if (m[0] == 'мая') { m[0] = '05' }
                        if (m[0] == 'июня') { m[0] = '06' }
                        if (m[0] == 'июля') { m[0] = '07' }
                        if (m[0] == 'августа') { m[0] = '08' }
                        if (m[0] == 'сентябрь') { m[0] = '09' }
                        if (m[0] == 'октября') { m[0] = '10' }
                        if (m[0] == 'ноября') { m[0] = '11' }
                        if ((m[0] == 'декабря') || (m[0] == 'December')) { m[0] = '12' }

                        let id = $(this).text();
                        let date = m[1]+'-'+m[0]+'-'+id;

                        $.get('http://fkolonistov.pythonanywhere.com/diary_note/'+date, function(data) {
                          // $(console.log(data));
                          var res = data.split('=');
                          $("#title").html(res[0]);
                          $(console.log(res[1]));
                          $("#text").html(res[1]);
                        });
                    });
                    let sel = $("#id_day");
                    sel.on('change', function(){
                      let d = $(this.options[this.selectedIndex]).val();
                      let w = $("#id_workout").val();
                      $.get('http://fkolonistov.pythonanywhere.com/workout_day/'+w+'/'+encodeURIComponent(d), function(data) {
                        $("#id_text").html(data);
                      });
                    });
                  });

                </script>

                <button type="submit" class="btn btn-outline-secondary" style="display:inline-block; margin-bottom:0.245rem;">Добавить запись</button>

            </form><br><br><br>
        </div>
    </div>

    <style>
        .month { width: 40rem; }
        tr { height: 4rem; }
       /* select {  } */
    </style>

{% endblock %}

<!--<table border="0" cellpadding="0" cellspacing="0" class="month">-->
<!--<tr><th colspan="7" class="month">декабря 2022</th></tr>-->
<!--<tr><th class="mon">Пн</th><th class="tue">Вт</th><th class="wed">Ср</th><th class="thu">Чт</th><th class="fri">Пт</th><th class="sat">Сб</th><th class="sun">Вс</th></tr>-->
<!--<tr><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="noday">&nbsp;</td><td class="thu">1</td><td class="fri">2</td><td class="sat">3</td><td class="sun">4</td></tr>-->
<!--<tr><td class="mon">5</td><td class="tue">6</td><td class="wed">7</td><td class="thu">8</td><td class="fri">9</td><td class="sat">10</td><td class="sun">11</td></tr>-->
<!--<tr><td class="mon">12</td><td class="tue">13</td><td class="wed">14</td><td class="thu">15</td><td class="fri">16</td><td class="sat">17</td><td class="sun">18</td></tr>-->
<!--<tr><td class="mon">19</td><td class="tue">20</td><td class="wed">21</td><td class="thu">22</td><td class="fri">23</td><td class="sat">24</td><td class="sun">25</td></tr>-->
<!--<tr><td class="mon">26</td><td class="tue">27</td><td class="wed">28</td><td class="thu">29</td><td class="fri">30</td><td class="sat">31</td><td class="noday">&nbsp;</td></tr>-->
<!--</table>-->

main/templates/main/exercise.html
{% extends 'main/index.html' %}
{% block main %}
    <div class="row">
        <h2 style="margin-bottom:20px;">Справочник упражнений</h2>
        <div class="col-md-3" id="{{guide_exercise.slug}}" style="margin-right:40rem;">
            <div class="card" style="width: 40rem; margin-right: 2rem; margin-bottom: 2rem;">
                <div class="card card-body">
                    <h5 class="card-title">{{guide_exercise.name}}</h5>
                    <p class="card-text">{{guide_exercise.desc}}</p>
                    {% if guide_exercise.video %}
                        <img src="{{ guide_exercise.video }}" class="card-img-top" style="width: 20rem; height: 20rem;" id="vid">
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/exercises.html
{% extends 'main/index.html' %}
{% block main %}
    <div class="row">
        <h2 style="margin-bottom:20px;">Справочник упражнений</h2>
        <div style="white-space: nowrap;display:inline-block;">
            <form action="{% url 'exercises' %}" method="get">
                <input name="q" type="text" value="{{ request.GET.q }}" placeholder="Поиск..." class="form-control" style="width:25rem;display:inline-block;">
                <button type="submit" class="btn btn-outline-secondary" style="display:inline-block; margin-bottom:0.245rem;">Найти</button>
            </form><br><br><br>
        </div>
        {% for e in guide_exercises %}
            <div class="col-md-3" id="{{e.slug}}" style="margin-right:40rem;">
                <div class="card" style="width: 40rem; margin-right: 2rem; margin-bottom: 2rem;">
                    <div class="card card-body">
                        <h5 class="card-title">{{e.name}}</h5>
                        <p class="card-text">{{e.desc}}</p>
                        <a href="{% url 'exercise' e.slug %}" style="color:black;">Показать</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

<script>
    $(function () {
        var ar = document.querySelectorAll("[id='vid_main']");
        // var a = $("#vid_main");
        $.each(ar, function(n, v) {
            console.log(n, v);
            v.on('mouseout', function() {
                $("#vid").css('display','none');
            });
            v.on('mouseover', function() {
                $("#vid").css('display','block');
            });
        });
    });
</script>

{% endblock %}

main/templates/main/home.html
{% extends 'main/index.html' %}
{% block main %}

    <div class="row">
        <h2 style="margin-bottom:20px;">Активные тренировки</h2>
        {% if active_workouts %}
            {% for aw in active_workouts %}
                <div class="col-md-3">
                    <div class="card" style="width: 18rem; height: 12rem; margin-right: 2rem; margin-bottom: 2rem;">
                      <img src="{{ aw.workout.photo.url }}" class="card-img-top" alt="..." style="height: 14rem; width: 18rem; border-radius: 3px;">
                      <div class="card card-body">
                        <h5 class="card-title">{{aw.workout.name}}</h5>
                        <p class="card-text">{{ aw.workout.desc|truncatechars:50 }}</p>
                        <a href="{% url 'workout' aw.workout.slug %}" class="btn btn-primary">Перейти к тренировке</a>
                      </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-md-3">
                <div style="white-space: nowrap;">
                    <p style="display: inline-block;">У Вас пока нет активных тренировок.</p>
                    <a href="{% url 'workouts' %}" style="text-decoration: none; margin-bottom: 5px; margin-left: 5px;" class="btn btn-outline-primary btn-sm">Подобрать тренировку</a>
                </div>
            </div>
        {% endif %}
    </div>
{% if active_workouts %}<br><br><br><br><br><br><br><br><br><br>{% endif %}

    {% if workouts %}
        <div class="row">
            <h2 style="margin-bottom:20px;">Программы тренировок</h2>
            {% for w in workouts %}
                <div class="col-md-3">
                    <div class="card" style="width: 18rem; height: 27.3rem; margin-right: 2rem; margin-bottom: 2rem;">
                      <img src="{{ w.photo.url }}" class="card-img-top" alt="..." style="height: 14rem; width: 18rem; border-radius: 3px;">
                        <div class="card card-body">
                            <h5 class="card-title">{{w.name}}</h5>
                            <p class="card-text">{{ w.desc|truncatechars:50 }}</p>
                            <a href="{% url 'workout' w.slug %}" class="btn btn-primary" style="position: absolute; margin-top:9rem;">Перейти к тренировке</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="col-md-3">
                <a href="{% url 'workouts' %}" class="btn btn-primary">Смотреть все</a>
            </div>
        </div>
    {% endif %}

    {% if recipes %}
        <div class="row">
            <h2 style="margin-bottom:20px;">Рецепты спортивного питания</h2>
            {% for recipe in recipes %}
                <div class="col-md-3" style="margin-left: 0.5rem;">
                    <div class="card" style="width: 18rem; height: 25rem; margin-right: 2rem; margin-bottom: 2rem;">
                      <img src="{{ recipe.photo.url }}" class="card-img-top" alt="..." style="height: 14rem; width: 18rem; border-radius: 3px;">
                        <div class="card card-body">
                            <h5 class="card-title">{{recipe.title}}</h5>
                            <p class="card-text">{{recipe.desc|truncatechars:50}}</p>
                            <a href="{% url 'recipe' recipe.slug %}" class="btn btn-primary" style="position: absolute; margin-top:7rem;">Перейти к рецепту</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

{% endblock %}

main/templates/main/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="/bower_components/bootstrap-horizon/bootstrap-horizon.css">
      <!-- jQuery -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.5.0.js"></script>

      <!-- Fengyuan Chen's Datepicker -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
    <title>{{title}}</title>
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <div class="wrapper">
        <!-- Sidebar -->
        <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px; height:100%; position: fixed; margin-right: 300px;">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
              <span class="fs-4">Онлайн Тренер</span>
            </a>
            <hr>
               <ul class="nav nav-pills flex-column mb-auto">
                    <li class="nav-item">
                        {% if 'Главная' == title %}
                            <a href="{% url 'home' %}" class="nav-link active" aria-current="page">
                        {% else %}
                            <a href="{% url 'home' %}" class="nav-link" style="color: white;" aria-current="page">
                        {% endif %}
                                <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                                Главная
                            </a>
                    </li>
                    <li class="nav-item">
                        {% if 'Тренировки' == title %}
                            <a href="{% url 'workouts' %}" class="nav-link active" aria-current="page">
                        {% else %}
                            <a href="{% url 'workouts' %}" class="nav-link" style="color: white;" aria-current="page">
                        {% endif %}
                                <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                                Тренировки
                            </a>
                    </li>
                   <li class="nav-item">
                        {% if 'Упражнения' == title %}
                            <a href="{% url 'exercises' %}" class="nav-link active" aria-current="page">
                        {% else %}
                            <a href="{% url 'exercises' %}" class="nav-link" style="color: white;" aria-current="page">
                        {% endif %}
                                <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                                Упражнения
                            </a>
                   </li>
                   <li class="nav-item">
                        {% if 'Рецепты' == title %}
                            <a href="{% url 'recipes' %}" class="nav-link active" aria-current="page">
                        {% else %}
                            <a href="{% url 'recipes' %}" class="nav-link" style="color: white;" aria-current="page">
                        {% endif %}
                                <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                                Рецепты
                            </a>
                   </li>
                   {% if request.user.is_authenticated %}
                       <li class="nav-item">
                            {% if 'Дневник тренировок' == title %}
                                <a href="{% url 'diary' %}" class="nav-link active" aria-current="page">
                            {% else %}
                                <a href="{% url 'diary' %}" class="nav-link" style="color: white;" aria-current="page">
                            {% endif %}
                                    <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                                    Дневник тренировок
                                </a>
                       </li>
                   {% endif %}
                   <br><br>
                   <li class="nav-item" style="margin-left:2.8rem;">
                       {% if request.user.is_authenticated %}
                           <div class="nav-item">
                               <p>{{user.username}}</p>
                           </div>
                           <div class="nav-item">
                               <a href="{% url 'logout' %}">Выйти</a>
                           </div>
                       {% else %}
                           <div class="nav-item">
                               <a href="{% url 'login' %}">Войти</a>
                           </div>

                           <div class="nav-item">
                               <a href="{% url 'signup' %}">Зарегистрироваться</a>
                           </div>
                       {% endif %}
                    </li>
            </ul>
        </div>
        <!--  end  -->

        <div class="container" style="margin-left: 20rem;">
            {% block main %}
            {% endblock %}
        </div>

    </div>
</body>
</html>